{% set version = '1.0-7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsvgtipsdevice
  version: {{ version|replace("-", "_") }}

source:
  url:     {{ cran_mirror }}/src/contrib/Archive/RSVGTipsDevice/RSVGTipsDevice_{{ version }}.tar.gz
  sha256: 4bdd0bad01a4a22158b511c74ac5261fa5acc9a94122fde8d67f920b0145b949

build:
  merge_build_host: True  # [win]
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('RSVGTipsDevice')"           # [not win]
    - "\"%R%\" -e \"library('RSVGTipsDevice')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RSVGTipsDevice
  license: GPL-2.0-or-later
  summary: A graphics device for R that uses the w3.org xml standard for Scalable Vector Graphics.  This
    version supports tooltips with 1 to 3 lines, hyperlinks, and line styles.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: RSVGTipsDevice
# Version: 1.0-7
# Date: 2016-07-19
# Title: An R SVG Graphics Device with Dynamic Tips and Hyperlinks
# Author: Tony Plate <tplate@acm.org>, based on RSvgDevice by T Jake Luciani <jakeluciani@yahoo.com>
# Maintainer: Tony Plate <tplate@acm.org>
# Depends: R (>= 2.6)
# Description: A graphics device for R that uses the w3.org xml standard for Scalable Vector Graphics.  This version supports tooltips with 1 to 3 lines, hyperlinks, and line styles.
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2016-07-21 22:33:38 UTC; tap
# Repository: CRAN
# Date/Publication: 2016-07-24 01:36:07
