travis:
  secure:
    BINSTAR_TOKEN: JzvcAU4OwkkDZUgEydfi7F89i49tcoW/UDSAq6lKzpANvccmPuRF6cP9iazzhlX+CzukOe2nflRuc+8lfETT6oYZph1ThIPTEWPmyzTu6U2oHJ8u9o6vjaA+UozYvlQRiEf7C2J8pnAIp91lfFTtJV3K0si/P2yxh03SVPg88803JUi/J87ZQ0+yY+Vb+3bLjpxD27DcRQga5hTIdeUPpU48Zrq1zT1lMuTy8T21+Jo637k4KKCKTq9I5Q65w9adsSx6wosajqyrOR6bmKnPJQDQSxIaz7LUU3AP9ZkZAMAKzAcZDumNT9jl5/q9IwBxsWnkpOiK53kd3OZEX+Z58hE4AT8D/Ruy2dUqE3liZe4+MxMQnJFnbnYt1aYJoz32TUsxgSoHF5I0JevlMF9Y1HAF2VQbz9SaRJQF1iCKEOWQ9LH9J3HoHRSQXDGxGwG6pq2L3GQ9cTilbZP9CABoZqzjFuX/l8h5suzCqMWNJsJhqwBmjwZlJ9dtQuTDukaI631+3ATmtqci+5oMAbZ/3Sls2n8uVLUG/ZSuWrxu3HzyD34E+wWZeuFMW+Ai1/CgoJ+Zb7kxF1xW9MxAVnY0C+X6iA9rO2wSdypAJoonphfHrC2XALrbF/pOGUuPyoaUyqEt07ivkwOGUblnmSxzNjoPyC9Ly/TKNeCsP+gL6EM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
