appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LNavirZDiknD30/6gQF6seBYiuaQzKSTfwrJwGdSHSmWFfrIJj3JU5AjVolPx9sg+UWO8PPF+fqq+b0gfnuDvaV70tDrkXkGPm1qTJ19Tfg5UTfkPOkl+RnLdJFi7fWgegR7/SaJNUeTivOMePa1UI5R0VVE7hma51N5NFM0Q5TzzcVmYvvD7MiFFZeqc2zaC/LgnrW3SAEXmHpEHsX1qyWexpAT8sqpdz9FyZfOKaMb5DQeq5uGXurCcb+SeZWzYItA05kP2RFKkxl+RycCMu4Ti9GByDkPrv2vf65onzyKDFtTs6O/8L/uxz9LtKtaCxWZSahcEZYSLjlTlsVpclL+5NAb/OvD8qhoXmWjRrtlBprBhEGWRgqYN8NYAllamk821AYUqs284yxNpytNPYGEM6Uok7H+BjW2E7SSjDULuGzvyMNHVNf+wzwabh2rA6XpvnWtTo1hKCA2pkf9Pixa+UA/Fx7p5teT0B2R+j6CJM66H5LOkakHTZNR6PAf4f5+tqno0mQpet/SWlVsi1mYpmlTA+j7T/ruNDy7wQF8CVgiq4SyJ+CofKTnta34D+p2nFQk52njQutoZu31TkBbJkTEzOlbsH3tiVUUvSzIdTEmip199SOO8sJwqP0YMLnRGc/MZTAkZaNhv1KhVC2V6U7dBVts0Ivgf3wwV8k=
conda_forge_output_validation: true
